#!/usr/bin/python
# vim:fdm=marker
#### import {{{
import os
import sys
import struct
from PIL import Image
#}}}

### getMB, Old function, shouldn't be used {{{1
def getMB(MBLine,stride,offset, numofline, numofcolumn):
  curMB = []
  for i in range(0,numofline):
    curMB.append(MBLine[i*stride + offset :i*stride + offset + numofcolumn])
  return curMB

def Data2Img(Params,FrameData): #{{{1
  Width     = Params["frame_width"]
  Height    = Params["frame_height"]

  imY = Image.fromstring("L", (Width, Height)    , FrameData["Y"])
  imU = Image.fromstring("L", (Width/2, Height/2), FrameData["U"])
  imV = Image.fromstring("L", (Width/2, Height/2), FrameData["V"])

  imU = imU.resize((Width, Height))
  imV = imV.resize((Width, Height))
  #imY = imY.resize((Width/2, Height/2))

  im  = Image.merge("YCbCr",(imY,imU,imV))
  return im

def readOneFrame(Params, FrameNum, FileNum):#{{{1

  BlockSize_Y = Params["frame_height"] * Params["frame_width"]
  BlockSize_UV = Params["frame_height"] * Params["frame_width"] / 2
  BlockSize_Total = BlockSize_Y + BlockSize_UV

  FrameData = {}
  if FileNum == 1:
    YUVFile = open(Params["filename1"],"r")
  else:
    YUVFile = open(Params["filename2"],"r")
  YUVFile.seek( BlockSize_Total * FrameNum, os.SEEK_SET)
  FrameData["Y"] = YUVFile.read( Params["frame_height"] * Params["frame_width"] )
  FrameData["U"] = YUVFile.read( Params["frame_height"] * Params["frame_width"] / 4)
  FrameData["V"] = YUVFile.read( Params["frame_height"] * Params["frame_width"] / 4)
  return FrameData

def getOneMBFromFrame(Params, MbX, MbY, FrameData):#{{{1
  TopLeftX = MbX * 16
  TopLeftY = MbY * 16

  stride = Params["frame_width"]

  if MbX >= Params["width_in_mb"] or MbY >= Params["height_in_mb"]:
    return "fail"

  if TopLeftY+16 >= Params["frame_height"]:
    iNumOfLinesInMB = Params["frame_height"] - TopLeftY
  else:
    iNumOfLinesInMB = 16 

  if TopLeftX+16 >= Params["frame_width"]:
    iNumOfColumnsInMB = Params["frame_width"] - TopLeftX
  else:
    iNumOfColumnsInMB = 16 

  curMB = []
  for i in range(0,iNumOfLinesInMB):
    curMB.append(FrameData[ ( TopLeftY + i ) * stride + TopLeftX :( TopLeftY + i )*stride + TopLeftX + iNumOfColumnsInMB])
  
  MbData = {}
  MbData["MbData"] = curMB
  MbData["NumOfLinesInMB"] = iNumOfLinesInMB
  MbData["NumOfColumnsInMB"] = iNumOfColumnsInMB
  return MbData

def printMB(MbData):#{{{1
  MB                = MbData["MbData"]
  iNumOfLinesInMB   = MbData["NumOfLinesInMB"]
  iNumOfColumnsInMB = MbData["NumOfColumnsInMB"]

  for i in range(0,iNumOfLinesInMB):
    if not i%4:
      print"---------------------------------------------------------------------------------------------------------"
    for j in range(0,iNumOfColumnsInMB):
      if not j%4:
        print "|",
      int1, = struct.unpack("B",MB[i][j])
      print "%-5d"% int1,
    print "|\n"

  print"---------------------------------------------------------------------------------------------------------"

def printDiff(MbData1,MbData2):#{{{1
  MB1               = MbData1["MbData"]
  MB2               = MbData2["MbData"]
  iNumOfLinesInMB   = MbData1["NumOfLinesInMB"]
  iNumOfColumnsInMB = MbData1["NumOfColumnsInMB"]
  for i in range(0,iNumOfLinesInMB):
    if not i%4:
      print"---------------------------------------------------------------------------------------------------------"
    for j in range(0,iNumOfColumnsInMB):
      if not j%4:
        print "|",
      int1, = struct.unpack("B",MB1[i][j])
      int2, = struct.unpack("B",MB2[i][j])
      diff = int1 - int2
      print "%-5d"% diff,
    print "|\n"

  print"---------------------------------------------------------------------------------------------------------"


def printAllMBs(Params,WhichFile):#{{{1
  for frame_n in range(0,Params["num_of_frames"]):
    FrameData = readOneFrame(Params, frame_n, WhichFile)
    FrameData = FrameData["Y"]
    for mb_y in range(0,Params["height_in_mb"]): 
      for mb_x in range(0, Params["width_in_mb"]):
        MbData = getOneMBFromFrame(Params, mb_x, mb_y, FrameData)
        print "FrameNum: %d"%frame_n
        print "MB: (%d,%d)"%(mb_x,mb_y)
        printMB(MbData)

def printOneMBOfASeq(Params, WhichFile, FrameNum, MbX, MbY): #{{{1
  FrameData = readOneFrame(Params, FrameNum, WhichFile)
  FrameData = FrameData["Y"]
  MbData = getOneMBFromFrame(Params, MbX, MbY, FrameData)
  printMB(MbData)

def findFirstDiff(Params):#{{{1
  for frame_n in range(0,Params["num_of_frames"]):
    FrameData1 = readOneFrame(Params, frame_n, 1)
    FrameData2 = readOneFrame(Params, frame_n, 2)
    FrameData1 = FrameData1["Y"]
    FrameData2 = FrameData2["Y"]
    for mb_y in range(0,Params["height_in_mb"]): 
      for mb_x in range(0, Params["width_in_mb"]):
        MbData1 = getOneMBFromFrame(Params, mb_x, mb_y, FrameData1)
        MbData2 = getOneMBFromFrame(Params, mb_x, mb_y, FrameData2)

        if not MbData1["MbData"] == MbData2["MbData"]:
          print "FrameNum: %d"%frame_n
          print "MB: (%d,%d)"%(mb_x,mb_y)
          printDiff(MbData1,MbData2)
          return
  print "Con!!! All MBs are the same"

def findFrameDiff(Params, FrameNum):#{{{1
  FrameData1 = readOneFrame(Params, FrameNum, 1)
  FrameData2 = readOneFrame(Params, FrameNum, 2)
  FrameData1 = FrameData1["Y"]
  FrameData2 = FrameData2["Y"]
  for mb_y in range(0,Params["height_in_mb"]):
    for mb_x in range(0, Params["width_in_mb"]):
      MbData1 = getOneMBFromFrame(Params, mb_x, mb_y, FrameData1)
      MbData2 = getOneMBFromFrame(Params, mb_x, mb_y, FrameData2)

      if not MbData1["MbData"] == MbData2["MbData"]:
        print "FrameNum: %d"%FrameNum
        print "MB: (%d,%d)"%(mb_x,mb_y)
        printDiff(MbData1,MbData2)
        return
  print "Con! No difference found"

def parseCfgFile():#{{{1
  Params={}

  cfgFile = open("compare.cfg","r")
  cfgLine = cfgFile.readline()
  (file1, file2, width, height, numFrame, firstDiff) = cfgLine.split()

  Params["filename1"] = file1
  Params["filename2"] = file2
  Params["frame_width"] = int(width)
  Params["frame_height"] = int(height)
  Params["num_of_frames"] = int(numFrame)
  Params["first_diff_only"] = int(firstDiff)

  width=int(width)
  height=int(height)
  numFrame = int(numFrame)
  firstDiff = int(firstDiff)

  width_in_mb = width/16
  if width%16:
    width_in_mb = width_in_mb + 1

  height_in_mb = height/16
  if height%16:
    height_in_mb = height_in_mb + 1

  Params["width_in_mb"] = width_in_mb
  Params["height_in_mb"] = height_in_mb
  return Params

def showOneFrame(Params, WhichFile, FrameNum):#{{{1
  Width     = Params["frame_width"]
  Height    = Params["frame_height"]

  FrameData = readOneFrame(Params, FrameNum, WhichFile)

  im  = Data2Img(Params,FrameData)
  im.show()

def cmdExeFindDiff(Params,ArgStrings):#{{{1
  if len(ArgStrings) == 0:
    findFirstDiff(Params)
  else:
    FrameNum = int(ArgStrings[0])
    findFrameDiff(Params, FrameNum)

def cmdExeHelp():#{{{1
  print "Sorry, no help :-P"

def cmdExePrintAllMB(Params,ArgStrings):#{{{1
  printAllMBs(Params, int(ArgStrings[0]))

def cmdExePrintAMB(Params,ArgStrings):#{{{1
  if len(ArgStrings) >= 4:
    printOneMBOfASeq(Params, int(ArgStrings[0]), int(ArgStrings[1]), int(ArgStrings[2]), int(ArgStrings[3]))
  else:
    print "Too few arguments"

def cmdExeQuit():#{{{1
  print "Quit!"
  sys.exit()

def cmdExeNotACommand():#{{{1
  print "what the hell do you want to do ?"

def cmdExeSeeAFrame(Params,ArgStrings):#{{{1
  if not len(ArgStrings) >= 2:
    print "Too few arguments!\n\tUsage: sf <WhichFile> <FrameNum>"
    return

  WhichFile = int(ArgStrings[0])
  FrameNum  = int(ArgStrings[1])
  showOneFrame(Params, WhichFile, FrameNum)

def CommandExecution(Params, CmdString, ArgStrings):#{{{1
  Operations = {
      "h"  : lambda: cmdExeHelp(),
      "fd" : lambda: cmdExeFindDiff(Params,ArgStrings),
      "p"  : lambda: cmdExePrintAMB(Params,ArgStrings),
      "pa" : lambda: cmdExePrintAllMB(Params,ArgStrings),
      "sf" : lambda: cmdExeSeeAFrame(Params,ArgStrings),
      "nc" : lambda: cmdExeNotACommand(),
      "q"  : lambda: cmdExeQuit(),
        }
  Operations.get(CmdString,lambda: cmdExeNotACommand())()
#Global {{{1


Params = parseCfgFile()
if len(sys.argv) > 1:
  CmdString = sys.argv[1]
  if len(sys.argv) > 2:
    ArgStrings = sys.argv[2:]
  else:
    ArgStrings = []
  CommandExecution(Params, CmdString, ArgStrings)
else:
  while 1:
    CommandLine = raw_input('Enter command:')

    SplittedCmd  = CommandLine.split()
    if len(SplittedCmd) > 0:
      CmdString = SplittedCmd[0]
    else:
      CmdString = "nc"
    if len(SplittedCmd) > 1:
      ArgStrings = SplittedCmd[1:]
    else:
      ArgStrings = []
    CommandExecution(Params, CmdString, ArgStrings)
